version: '3.7'

services:
    monetex-nginx:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        image: nginx:1.15-alpine
        ports:
            - '80:80'
        volumes:
            - ./docker/nginx/conf:/etc/nginx/conf.d
