version: '3.7'

services:
    nginx:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        image: nginx:1.15-alpine
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./docker/nginx/conf:/etc/nginx/conf.d
            - ./docker/certbot/conf:/etc/letsencrypt
            - ./docker/certbot/www:/var/www/certbot
    certbot:
        image: certbot/certbot
        volumes:
            - ./docker/certbot/conf:/etc/letsencrypt
            - ./docker/certbot/www:/var/www/certbot
