version: '3.7'

services:
    nginx:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./build:/var/www
            - ./docker/nginx/conf:/etc/nginx/conf.d
            - ./docker/certbot/conf:/etc/letsencrypt
            - ./docker/certbot/www:/var/www/certbot
    django:
        build:
            context: .
            dockerfile: ./docker/server/Dockerfile
        command: bash -c "python3 src/manage.py collectstatic --noinput && python3 src/manage.py runserver 0.0.0.0:8000"
        volumes:
            - ./server:/server
        ports:
            - '8000:8000'

    certbot:
        image: certbot/certbot
        volumes:
            - ./docker/certbot/conf:/etc/letsencrypt
            - ./docker/certbot/www:/var/www/certbot
