version: '3.7'

services:
    nginx:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./build:/var/www
            - ./docker/nginx/conf:/etc/nginx/conf.d
            - ./docker/certbot/conf:/etc/letsencrypt
            - ./docker/certbot/www:/var/www/certbot

    # react:
    #     build:
    #         context: .
    #         dockerfile: ./docker/react/Dockerfile
    #     ports:
    #         - '80:3000'
    #     volumes:
    #         - ./:/app
    django:
        build:
            context: .
            dockerfile: ./docker/server/Dockerfile
        command: bash -c "python src/manage.py makemigrations && python src/manage.py makemigrations core && python src/manage.py migrate && python src/manage.py runserver 0.0.0.0:8000"
        volumes:
            - ./server:/server
        ports:
            - '8000:8000'
    certbot:
        image: certbot/certbot
        volumes:
            - ./docker/certbot/conf:/etc/letsencrypt
            - ./docker/certbot/www:/var/www/certbot
